version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - hasta_network

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: hasta_kayit
      MYSQL_USER: deneme2
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "3308:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql


    networks:
      - hasta_network

volumes:
  dbdata:

networks:
  hasta_network:
